// <auto-generated />
namespace TicketFinalSys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ReqFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReqFields));
        
        string IMigrationMetadata.Id
        {
            get { return "202012050235249_ReqFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
